spring:
  application:
    name: voting-backend
  datasource:
    password: ${DATABASE_PASSWORD:trophy}
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5555/voting}
    username: ${DATABASE_USERNAME:tamtour}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/api/login/oauth2/code/{registrationId}"
            scope: openid, profile, email
        provider:
          google:
            issuer-uri: https://accounts.google.com
server:
  servlet:
    session:
      cookie:
        http-only: true
  forward-headers-strategy: framework
logging:
  level:
    org.springframework.security: DEBUG
    ch.rafaelurben>.tamtour: DEBUG
app:
  admin_emails: ${ADMIN_EMAILS:}
