name: CI Backend

on:
  pull_request:
    paths:
      - 'voting-backend/**'

jobs:
  backend-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: voting-backend
    services:
      postgres:
        image: postgres:15
        ports: [ '5432:5432' ]
        env:
          POSTGRES_USER: tamtour
          POSTGRES_PASSWORD: trophy
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: jdbc:postgresql://localhost:5432/testdb
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 24
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '24'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Run Spotless Check
        run: ./gradlew spotlessCheck
      - name: Run Tests
        run: ./gradlew test
