name: CI Backend

on:
  pull_request:
    paths:
      - 'voting-backend/**'

jobs:
  backend-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: voting-backend
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 24
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '24'
          cache: 'gradle'
      - name: Run Spotless Check
        run: ./gradlew spotlessCheck
      - name: Run Tests
        run: ./gradlew test
