name: CI Frontend

on:
  pull_request:
    paths:
      - 'voting-frontend/**'

jobs:
  frontend-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: voting-frontend
    steps:
      - uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          cache: 'npm'
          node-version: '22'
      - name: Install dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint

